#!/usr/bin/env python3
"""
Test AI Description Generation Endpoint
"""

import requests
import json

def test_ai_description():
    """Test the AI description generation endpoint"""
    url = "http://localhost:8000/api/v1/products/test-product/generate-description"
    
    # Test product data
    product_data = {
        "title": "Modern Leather Sofa",
        "brand": "TestBrand", 
        "material": "Leather",
        "categories": "Furniture, Sofas",
        "price": "$299.99",
        "description": "A comfortable leather sofa"
    }
    
    print("Testing AI Description Generation Endpoint...")
    print(f"URL: {url}")
    print(f"Product Data: {json.dumps(product_data, indent=2)}")
    print("-" * 50)
    
    try:
        response = requests.post(url, json=product_data, timeout=30)
        
        print(f"Status Code: {response.status_code}")
        
        if response.status_code == 200:
            result = response.json()
            print("SUCCESS: AI Description Generated!")
            print(f"Product ID: {result.get('product_id', 'N/A')}")
            print(f"AI Description: {result.get('ai_description', 'N/A')}")
            print(f"Original Description: {result.get('original_description', 'N/A')}")
            print(f"Generated By: {result.get('generated_by', 'N/A')}")
        else:
            print(f"ERROR: Request failed with status {response.status_code}")
            print(f"Response: {response.text}")
            
    except Exception as e:
        print(f"ERROR: Exception occurred - {e}")

if __name__ == "__main__":
    test_ai_description()
