import React from "react";
import { useParams } from "react-router-dom";
import {
  Box,
  Typography,
  Card,
  CardContent,
  CardMedia,
  Chip,
  Button,
  Grid,
} from "@mui/material";
import { ArrowBack as ArrowBackIcon } from "@mui/icons-material";
import { useNavigate } from "react-router-dom";

const ProductDetailPage: React.FC = () => {
  const { id } = useParams<{ id: string }>();
  const navigate = useNavigate();

  // TODO: Fetch product details from API
  const product = {
    id: id || "1",
    title: "Sample Product Title",
    brand: "Sample Brand",
    price: "$99.99",
    description:
      "This is a sample product description that would be generated by AI.",
    image: "https://via.placeholder.com/400x300",
    categories: ["Home & Kitchen", "Furniture", "Chairs"],
    material: "Wood",
    country: "China",
  };

  return (
    <Box>
      <Button
        startIcon={<ArrowBackIcon />}
        onClick={() => navigate(-1)}
        sx={{ mb: 2 }}
      >
        Back
      </Button>

      <Grid container spacing={3}>
        <Grid item xs={12} md={6}>
          <Card>
            <CardMedia
              component="img"
              height="400"
              image={product.image}
              alt={product.title}
            />
          </Card>
        </Grid>

        <Grid item xs={12} md={6}>
          <Card>
            <CardContent>
              <Typography variant="h4" gutterBottom>
                {product.title}
              </Typography>

              <Typography variant="h6" color="primary" gutterBottom>
                {product.price}
              </Typography>

              <Typography variant="body2" color="text.secondary" gutterBottom>
                Brand: {product.brand}
              </Typography>

              <Typography variant="body2" color="text.secondary" gutterBottom>
                Material: {product.material}
              </Typography>

              <Typography variant="body2" color="text.secondary" gutterBottom>
                Country: {product.country}
              </Typography>

              <Box sx={{ mt: 2, mb: 2 }}>
                {product.categories.map((category) => (
                  <Chip key={category} label={category} sx={{ mr: 1, mb: 1 }} />
                ))}
              </Box>

              <Typography variant="h6" gutterBottom>
                Description
              </Typography>
              <Typography variant="body1" paragraph>
                {product.description}
              </Typography>

              <Button variant="contained" size="large" fullWidth>
                Add to Cart
              </Button>
            </CardContent>
          </Card>
        </Grid>
      </Grid>
    </Box>
  );
};

export default ProductDetailPage;
